# Generated by Django 2.2.4 on 2019-10-30 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20191029_1622'),
        ('crm', '0002_product_service'),
    ]

    operations = [
    ]
